### ISSUE TITLE
Black screen and mister frozen

### ISSUE THREAD

**Issue by asturur** [va7deo/TerraCresta#1]
Hi All,
i know this is a beta and as such it comes with some rough edges.
My current experience is that as soon as i launch the core i get a black screen in both analog and hdmi output, and the mister is frozen and does not take the hardware reset, so i have to pull the plug.
Suggestions?

**Comment by atrac17** [comment]
This indicates the files you have copied over for Terra Cresta are corrupted on your storage medium. If you remove them, this should fix the issue.

**Comment by asturur** [comment]
the latest beta does not crash anymore for me.
So either my rbf got corrupted during copy from windows, twice, or there was something else that went away with latest beta. Anyway now works good. thanks

**Comment by asturur** [comment]
This was the thing i tried to do before opening the issue.
Deleted the rbf, the rma, and a single zip from games folder.
Added back the rbf from github and the rmas, then run update all to get a
rom back.

How many roms zip the games has? if more than one i may have missed some to
delete.
